name: Launch

on: [push]

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Build
        run: |
          go build -v foguete.go
      - name: Launch
        run: |
          ./foguete
      - name: Package
        run: |
          cd orbita
          tar -cvz . > ../site.tar.gz
      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            hut
      - name: Push
        ## if: github.ref == 'refs/heads/master'
        shell: alpine.sh {0}
        run: |
          mkdir -p ~/.config/hut
          echo "instance \"sr.ht\" { access-token-cmd echo \$SRHT_TOKEN }" > ~/.config/hut/config
          cat ~/.config/hut/config
          hut meta show
